/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "stm32f1xx.h"
#include"main.h"
unsigned char lcd_buff1[17];
unsigned char lcd_buff2[17];
void delay_ms(uint32_t ms)
{
    for(uint32_t i = 0; i < ms * 8000; i++)
        __NOP();
}
int main(void)
{
    /* Loop forever */
	clk_init();
	CAN_init();
	uint8_t data[3];
	uint8_t dlc;
	uint16_t id;
	uint8_t left;
	uint8_t right;
	uint8_t headlamp;


	while(1)
	{
		if(CAN_receive(&id,data,&dlc)==0)
		{
			//extract data
			uint8_t speed=data[0];
			uint8_t switches=data[1];
			uint8_t temp =data[2];

			//decoding switches
			 left = switches & 0x01;
			 right = (switches >> 1) & 0x01;
			 headlamp = (switches >> 2) & 0x01;

			lcd_display(speed, left, right, headlamp, temp);

		}

		//headlamp
		if (headlamp)
			GPIOB->BSRR = GPIO_BSRR_BS2;   // PB2 ON
		else
			GPIOB->BSRR = GPIO_BSRR_BR2;   // PB2 OFF

		// left indicator
		if (left)
		    {
		        GPIOB->BSRR = GPIO_BSRR_BS0;   // ON
		        delay_ms(300);
		        GPIOB->BSRR = GPIO_BSRR_BR0;   // OFF
		        delay_ms(300);
		    }
		else
		    {
		        GPIOB->BSRR = GPIO_BSRR_BR0;   // OFF
		    }


		//right  indicator
		 if (right)
		    {
		        GPIOB->BSRR = GPIO_BSRR_BS1;   // ON
		        delay_ms(300);
		        GPIOB->BSRR = GPIO_BSRR_BR1;   // OFF
		        delay_ms(300);
		    }
		 else
		    {
		        GPIOB->BSRR = GPIO_BSRR_BR1;   //  OFF
		    }
	}
}
