/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
#include "main.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

int main(void)
{
	clk_init();
	CAN_init();
	ADC1_init();
	GPIO_init();
	uint8_t data[3]={0};

    /* Loop forever */
	while(1)
	{
		//speed
		uint16_t speed=adc1_read_channel(1);     //PA1
		data[0]=(speed*100)/4095;

		// swithces
		data[1]=read_switches();

		//temperture
		uint16_t temp=adc1_read_channel(0);  //PA0
		float temp_f = (temp * 3.3f) / 4095.0f / 0.01f; // Convert to °C
		data[2] = (uint8_t)temp_f;

		// transmitting can frame
		CAN_transmit(0x100, data, 3);  // Std ID = 0x100, DLC = 4

		//delay
		for(volatile int i=0; i<500000; i++);
	}
}
